### ISSUE TITLE
Disabling a plugin causes floatPrecision to be ignored

### ISSUE THREAD

**Issue by jlherren** [svg/svgo#1407]
**Describe the bug**
According to the README, the way to disable a single plugin is as follows (`svgo.config.js`):
```
const {extendDefaultPlugins} = require('svgo');
module.exports = {
    floatPrecision: 1,
    plugins: extendDefaultPlugins([
        {
            name:   'cleanupIDs',
            active: false,
        },
    ]),
};
```

However, this seems to cause `floatPrecision` to be ignored as numbers are no longer rounded.

My input SVG:
```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
<path id="clip" fill="none" stroke="#9160AD" stroke-width="0.25" stroke-miterlimit="10" d="M13.332,9.362l-5.22,5.22
	c-0.614,0.614-0.614,1.535,0,2.149c0.614,0.614,1.535,0.614,2.149,0l7.293-7.293c0.998-0.998,0.998-2.61,0-3.608l0,0
	c-0.998-0.998-2.61-0.998-3.608,0l-7.83,7.83c-1.305,1.305-1.305,3.378,0,4.683l0,0c1.305,1.305,3.378,1.305,4.683,0l8.137-8.06"/>
</svg>
```

Output **without** the `plugins` value in the options (newlines added for readability):
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" xml:space="preserve">
<path fill="none" stroke="#9160AD" stroke-width=".3" stroke-miterlimit="10" 
d="m13.3 9.4-5.2 5.2c-.6.6-.6 1.5 0 2.1.6.6 1.5.6 2.2 0l7.3-7.3A2.5 2.5 0 1 0 14 5.8L6 13.7a3.3 3.3 0 0 0 0 4.6 3.3 3.3 0 0 0 4.7 0l8.1-8"/>
</svg>
```

Output **with** the `plugins` value in the options (newlines added for readability):
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" xml:space="preserve">
<path id="clip" fill="none" stroke="#9160AD" stroke-width=".25" stroke-miterlimit="10" 
d="m13.332 9.362-5.22 5.22c-.614.614-.614 1.535 0 2.149.614.614 1.535.614 2.149 0l7.293-7.293a2.548 2.548 0 0 0 0-3.608 2.548 2.548 0 0 0-3.608 0l-7.83 7.83a3.29 3.29 0 0 0 0 4.683 3.29 3.29 0 0 0 4.683 0l8.137-8.06"/>
</svg>
```

If I specify `--precision 1` on the command line it gets ignored in the same way.

**Comment by TrySound** [comment]
Good catch. Fixed it here https://github.com/svg/svgo/commit/d58a7e6089ccf15ecc3928427d55e6b9601094af

**Comment by TrySound** [comment]
Fixed in v2.2.1

**Comment by jlherren** [comment]
I'm afraid, but the bug is still present with the very example I posted originally. It seems like the value of `floatPrecision` gets inherited into all plugins, except the ones that define their own default value for `floatPrecision`.
