### ISSUE TITLE
Svgo broke a few files

### ISSUE THREAD

**Issue by iliakan** [svg/svgo#338]
The new version is much better, but it still breaks files sometimes.

I have 3 broken files, probably the reason is the same, because they are similar.

Github does not support SVG uploading, so I zipped both sources and originals and put'em here https://www.dropbox.com/s/i1brbfjbl30enw2/svg.opt.zip?dl=0

Great to see the progress!

**Comment by tssajo** [comment]
I can also show you one which gets broken when minified with v0.5.1 while it did look fine when processed with v0.5.0
You can download the original and the broken SVG files from http://www.tssajo.com/github/svg_got_broken.zip

**Comment by GreLI** [comment]
Fixed in 97a260bbf3a75764f250a56422b97719b9768a63 (rotate() optional parameters)  and in f68b310c1ea43b476e6fcf1aae6bdfc2d2b4d7f6 (the car)

**Comment by iliakan** [comment]
@GreLI please release a new version when you feel like it's ready :) 
I'll retest immediately.

**Comment by andrei1089** [comment]
I've tried with the latest version (https://github.com/svg/svgo/commit/97a260bbf3a75764f250a56422b97719b9768a63) but the following image is still broken: https://drive.google.com/file/d/0BwW_lFF0AAQZNHVJdXQwSEZEY0E/view?usp=sharing

**Comment by GreLI** [comment]
[v0.5.2](/svg/svgo/releases/tag/v0.5.2) with the fix has been just released.
