### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by vmarkovtsev** [svg/svgo#352]
svgo 0.5.1 breaks on the following image created in Inkscape: https://mega.co.nz/#!JAIwiZJT!K3GB7tUl2X9CF5zTGr_9eTs78CUKMB3z4VA07XFOpLY

```
svgo/lib/svgo/svg2js.js:152
        while (start && !start.text) start = start.content[0];
                                                          ^
TypeError: Cannot read property '0' of undefined
    at trim (svgo/lib/svgo/svg2js.js:152:59)

```

**Comment by GreLI** [comment]
Likely it was fixed in 1151e44c5af4aee5ab44f3cef20e401b66a734e2.

**Comment by jimniels** [comment]
Still doesn't work for me ... Same issue as mentioned here https://github.com/sindresorhus/grunt-svgmin/issues/38

    svgo -v
    0.5.1

**Comment by paperboyo** [comment]
Hi,

Could this https://github.com/jakearchibald/svgomg/issues/20 be possibly related?

Regards
m.

**Comment by jimniels** [comment]
That appears to have worked! Disabling mergePaths in my grunt config seems to have solved the issue:

```
options: {
    plugins: [{mergePaths: false}]
},
```
With this, my svgmin task ran through all the files and optimized them just fine.

**Comment by GreLI** [comment]
Odd, it's totally fine to me.

**Comment by GreLI** [comment]
Oh, I see. You are using the latest released version, while there were some fixes since then, including the one I've mentioned.

**Comment by GreLI** [comment]
[v0.5.2](/svg/svgo/releases/tag/v0.5.2) with the fix has been just released.

**Comment by vmarkovtsev** [comment]
Thanks!
