### ISSUE TITLE
--enable=convertPathData (default), throws an error

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#949]
Prozessing [File:Welcome_to_Fabulous_Las_Vegas_Sign.svg](https://commons.wikimedia.org/wiki/File:Welcome_to_Fabulous_Las_Vegas_Sign.svg) with svgo throws an error.

> svgo -i [input.svg](https://upload.wikimedia.org/wikipedia/commons/archive/1/15/20090509132757%21Welcome_to_Fabulous_Las_Vegas_Sign.svg) -o output.svg

[input.svg.txt](https://github.com/svg/svgo/files/1904938/input.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2755.7 2400.1">
 <path d="m-620.23 512.94a87.88 80.81 0 01-87.88 80.81 87.88 80.81 0 01-87.88-80.81 87.88 80.81 0 0187.88-80.81 87.88 80.81 0 0187.88 80.81z"/>
</svg>

```
throws an error
```bash
TypeError: Cannot read property 'toFixed' of undefined
    at strongRound (C:\Users\jkalliau\AppData\Roaming\npm\node_modules\svgo\plugins\convertPathData.js:766:21)
    at C:\Users\jkalliau\AppData\Roaming\npm\node_modules\svgo\plugins\convertPathData.js:424:17
    at Array.filter (<anonymous>)
    at filters (C:\Users\jkalliau\AppData\Roaming\npm\node_modules\svgo\plugins\convertPathData.js:272:17)
    at Object.exports.fn (C:\Users\jkalliau\AppData\Roaming\npm\node_modules\svgo\plugins\convertPathData.js:79:20)
    at C:\Users\jkalliau\AppData\Roaming\npm\node_modules\svgo\lib\svgo\plugins.js:61:45
    at Array.filter (<anonymous>)
    at monkeys (C:\Users\jkalliau\AppData\Roaming\npm\node_modules\svgo\lib\svgo\plugins.js:48:39)
    at C:\Users\jkalliau\AppData\Roaming\npm\node_modules\svgo\lib\svgo\plugins.js:68:17
    at Array.filter (<anonymous>)
```

It might be similar to a solved bug in scour:  https://github.com/scour-project/scour/issues/161

**Comment by GreLI** [comment]
That's because of flags without separator (`01`), see #822.

**Comment by GreLI** [comment]
Fixed in 3c82fd7287522e65ab0303834beaf7a92260cbe6.

**Comment by JoKalliauer** [comment]
@GreLI How can I update to the latest development-version?
I tried `npm install -g svgo` and restarted the terminal, but this error still occours, therefore I think I didn't update to  3c82fd7 .

**Comment by GreLI** [comment]
Yep, it's not released yet. I'm planning to release today, until then it can be achieved from Githbub repositary.

**Comment by JoKalliauer** [comment]
>, until then it can be achieved from Github repositary. 

How can it be achived from Github repositary?
